//
// Created by max on 04/02/25.
//
#pragma once

#include "CBaseVisitor.h"  // Generated by ANTLR from your grammar (C.g4)
#include <any>

class CInterpreterVisitor : public CBaseVisitor {

public:
    std::any visitEvaluateExpression(CParser::EvaluateExpressionContext *ctx) override;
    std::any visitAddSubExpression(CParser::AddSubExpressionContext *ctx) override;
    std::any visitMulDivExpression(CParser::MulDivExpressionContext *ctx) override;
    std::any visitParenthesizedExpression(CParser::ParenthesizedExpressionContext *ctx) override;
    std::any visitNumberExpression(CParser::NumberExpressionContext *ctx) override;
    std::any visitUnaryMinusExpression(CParser::UnaryMinusExpressionContext *ctx) override;
};




